config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/search', to: 'microposts#search'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :passwords, only: [:edit, :update]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :micropost, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: "User", foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<li id="notification-<%= notification.id %>">
  <% visitor = notification.visitor %>
  <% visited = notification.visited %>
  <div class = "col-md-6.mx-auto" >
    <div class = "form-inline">
      <span>
        <%= link_to user_path(visitor) do %>
          <%= gravatar_for(visitor, size: 50) %>
          <strong><%= visitor.name %></strong>
        <% end %>
        <%= 'さんが' %>
        <% case notification.action %>
        <% when 'follow' then %>
          <%= "あなたをフォローしました" %>
        <% when 'like' then %>
          <%= link_to 'あなたの投稿', notification.micropost, style: "font-weight: bold;" %>
          <%= "にいいねしました" %>
        <% when 'comment' then %>
          <% if notification.micropost.user_id == visited.id %>
            <%= link_to "あなたの投稿", notification.micropost, style: "font-weight: bold;" %>
          <% else %>
            <span>
              <%= link_to micropost_path(notification.micropost) do %>
                <%= gravatar_for(notification.micropost.user, size: 50) %>
                <strong><%= notification.micropost.user.name + 'さんの投稿' %></strong>
              <% end %>
            </span>
          <% end %>
          <%= "にコメントしました" %>
          <p class = "text-muted mb-0"><%= Comment.find_by(id: notification.comment_id)&.content %></p>
        <% end %>
      </span>
    </div>
  </div>
  <span class="timestamp">
    <%= time_ago_in_words(notification.created_at) %>前
  </span>
</li>  

app/views/notifications/index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<% if notifications.exists? %>
  <ol class = notifications >
    <%= render notifications %>
  </ol>
<% else %>
  <p>通知はありません</p>
<% end %> 