config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/search', to: 'microposts#search'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :passwords, only: [:edit, :update]
end

app/views/shared/_bell.html.erb
<%= link_to(notifications_path) do %>
  <% if unchecked_notifications.any? %>
    <span class = 'fa-stack'>
      <i class="fa fa-bell-o fa-lg fa-stack-2x" style="font-size: 1.5em;"  aria-hidden="true"></i>
      <i class = 'fa fa-circle n-circle fa-stack-1x' aria-hidden = 'true'></i>.
    </span>
  <% else %>
  <i class="fa fa-bell-o fa-lg fa-stack-2x" style="font-size: 1.5em;"  aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <%= f.text_area :content, placeholder: "画像をアップして投稿しよう..." %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script

app/views/shared/_search.html.erb
<%= form_tag '/search', :method => 'get' do %>
  <div class="input-group">
    <%= text_field_tag :search, params[:search], placeholder: "キーワード検索", class: "form-control" %>
    <span class="input-group-btn">
        <%= button_tag "検索", name: nil, class: "btn btn-primary" %>
    </span>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー中
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= "#{current_user.microposts.count}件の投稿" %></span>