config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/search', to: 'microposts#search'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :passwords, only: [:edit, :update]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }
  validates :picture, presence: true
  validate  :picture_size

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and micropost_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        micropost_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(micropost_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      micropost_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def self.search(search)
    if search
      Micropost.where(['content LIKE ?', "%#{search}%"])
    else
      Micropost.all
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user,   only: :destroy

  def new
    @micropost = Micropost.new
  end

  def show
    @micropost = Micropost.find(params[:id])
    @user = User.find(@micropost.user_id)
    @comments = @micropost.comments
    @comment = Comment.new
    respond_to do |format|
      format.html { render 'microposts/_show' }
      format.js
    end
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿しました！"
      redirect_to root_url
    else
      @feed_items = []
      render new_micropost_path
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end

  def search
    @microposts = Micropost.search(params[:search])
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user, remote: true %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <div class = "text"><%= micropost.content %></div>
    <% if micropost.picture? %>
      <%= link_to image_tag(micropost.picture.url), micropost_path(micropost) %>
    <% end %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>前
    <% if current_user?(micropost.user) %>
      <%= link_to "削除", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
    <%= render "likes/like", micropost: micropost %>
  </span>
</li>

app/views/microposts/_show.html.erb
<div class = "modal-dialog micropost-modal">
  <div class = "modal-content">
    <% provide(:title, "#{@user.name}\'s post #{@micropost.content}") %>
    <div class = "micropost">
      <%= render @micropost %>
    </div>
    <div class = "comment-wrapper border-top mb-10">
      <% if @comments.empty? %>
        <h3>コメントはまだありません</h3>
      <% else %>
        <h3><%= "#{@comments.count}件のコメント" %></h3> 
        <div class = "comments" >
          <% @comments.each do |comment| %>
            <li>
              <span class = "user"><%= link_to comment.user.name, comment.user %></span>
              <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
              <span class = "content">
                <div class = "text"><%= comment.content %></div>
              </span>
              <span class = "timestamp">
                <%= time_ago_in_words(comment.created_at || Time.now) %>前
                <% if current_user?(comment.user) %>
                  <%= link_to "削除", micropost_comment_path(comment.micropost.id, comment.id), method: :delete, data:{ confirm: "You sure?" } %>
                <% end %>
              </span>
            </li>
          <% end %>
        </div>
      <% end %>
      <%= form_with(model: [@micropost, @comment], local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.text_area :content, placeholder: "コメントを入力して下さい..." %>
        </div>
        <%= f.submit "コメントする", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/microposts/new.html.erb
<% provide(:title, "Post") %>
<h1>投稿する</h1>
<div class="row">
  <aside class="col-md-12">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
</div>

app/views/microposts/search.html.erb
<% if @microposts.blank? %>
  <p>一致する結果はありません</p>
<% else %>
  <ol class = microposts >
    <%= render @microposts %>
  </ol>
<% end %> 

app/views/microposts/show.js.erb
$("#micropost-modal").html("<%= escape_javascript(render('microposts/show')) %>");
$("#micropost-modal").modal("show")